package com._glab.booking_system;

public enum ErrorResponseCode {
    USER_EMAIL_NOT_VALID,
    USER_EMAIL_ALREADY_EXISTS,
    USER_USERNAME_ALREADY_EXISTS,
    USER_INVALID_ROLE,

    // Authentication / JWT
    AUTH_INVALID_TOKEN,
    AUTH_EXPIRED_TOKEN,
    AUTH_INVALID_CREDENTIALS,
    AUTH_ACCOUNT_DISABLED,
    AUTH_ACCOUNT_LOCKED,

    // Refresh tokens
    AUTH_INVALID_REFRESH_TOKEN,
    AUTH_REFRESH_TOKEN_EXPIRED,
    AUTH_REFRESH_TOKEN_REUSE_DETECTED,

    // Password setup / reset tokens
    AUTH_PASSWORD_TOKEN_INVALID,
    AUTH_PASSWORD_TOKEN_EXPIRED,

    // MFA (Multi-Factor Authentication)
    AUTH_MFA_REQUIRED,
    AUTH_MFA_SETUP_REQUIRED,
    AUTH_MFA_INVALID_CODE,
    AUTH_MFA_CODE_EXPIRED,
    AUTH_MFA_TOKEN_INVALID,
    AUTH_MFA_TOKEN_EXPIRED,
    AUTH_MFA_RATE_LIMITED,
    AUTH_MFA_ALREADY_ENABLED,
    AUTH_MFA_NOT_ENABLED,
    AUTH_MFA_CANNOT_DISABLE,

    // Booking - Resources
    BOOKING_LAB_NOT_FOUND,
    BOOKING_WORKSTATION_NOT_FOUND,
    BOOKING_RESERVATION_NOT_FOUND,
    BOOKING_BUILDING_NOT_FOUND,

    // Booking - Validation
    BOOKING_INVALID_TIME_RANGE,
    BOOKING_OUTSIDE_OPERATING_HOURS,
    BOOKING_LAB_CLOSED,
    BOOKING_WORKSTATION_NOT_IN_LAB,
    BOOKING_WORKSTATION_INACTIVE,
    BOOKING_NO_WORKSTATIONS_SELECTED,

    // Booking - Recurring
    BOOKING_INVALID_RECURRING_PATTERN,
    BOOKING_NO_VALID_OCCURRENCES,

    // Booking - Permissions
    BOOKING_NOT_AUTHORIZED,
    BOOKING_NOT_LAB_MANAGER,
    BOOKING_NOT_RESERVATION_OWNER,

    // Booking - Edit Proposals
    BOOKING_EDIT_PROPOSAL_NOT_FOUND,
    BOOKING_INVALID_EDIT,
    BOOKING_EDIT_ALREADY_RESOLVED,

    // Booking - State Errors
    BOOKING_INVALID_STATE
}
